BIGTOP-2882: Bump Hadoop to 2.8.1
That patch also bump Hbase to 1.3.1 and Pig to 0.17.0

Pig changes:

    Bump Pig to 0.17.0.
    Remove useless patches PIG-4676 and PIG-4728
    because  it is already in 0.17 release.
    Add patch PIG-5304 to build pig with Hadoop 2.8

Hbase changes:
    There are a number of issues with licenses check when hbase
    building with Hadoop 2.8.x

    That patch bump hbase to latest release and add couple patches.

Hadoop changes:

    fuse_dfs target dir has been changed in 2.8
    HADOOP-12366 has been ported to 2.8.1
    HADOOP-11628 was merged in 2.8.x so removes it.

    Add package goal to mvn. Without that goal tar is incomplete:

    + for dir in '${HADOOP_DIR}/{lib,}' '${HDFS_DIR}/{lib,}' '${YARN_DIR}/{lib,}' '${MAPREDUCE_DIR}/{lib,}'
    + '[' -e /code/build/hadoop/rpm/BUILDROOT/hadoop-2.8.1-243.el7.centos.x86_64/usr/lib/hadoop-mapreduce//hadoop-common-2.8.1.jar ']'
    + exit 1
    error: Bad exit status from /var/tmp/rpm-tmp.5Etrah (%install)
    Bad exit status from /var/tmp/rpm-tmp.5Etrah (%install)